### ISSUE TITLE
Corrections in Model

### ISSUE THREAD

**Issue by chintans** [Promact/testcase-management-suite#15]
There are some mis-understanding regarding TestCase Model

As per discussion Pre-Condition could be a previous test case or a string. Pre-Conditions can have multiple values. Please correct Model accordingly.

None of the base classes are marked abstract. It is a best practice to create base class as abstract class.

TestCaseVersion -> TCID , This is not the naming conventions we follow

How will you connect a Module with a Project?

How will you connect a Scenario with a Project?

**Comment by Krunal-Promact** [comment]
- Base models were made abstract, But there was a merge issue from development. so when development code merged with master branch, that changes were lost. You can see there was a separate commit with commit id e568c38 exist in history, which comprise changes regarding making base model abstract.
- The naming convention of TCID is not proper. It is my mistake.
- The mapping between project and module and project and scenario is missing. It is also my mistake.
- I think we did not have any discussion regarding preconditions. Either I am not remembering it or there is some misunderstanding regarding it.

**Comment by Krunal-Promact** [comment]
- Changes from my side. There is already one field in base class exist with name TestCaseId which is as per the convention we follow. so due to this conflict, i named it as TCID. And that TestCaseId filed in base Test Case class contains alphanumeric id that tester uses to uniquely identify each test case.

**Comment by Krunal-Promact** [comment]
Models updated in branch dashboard-integration. @chintans Please provide your feedback.

**Comment by chintans** [comment]
Create a pull request for review
