### ISSUE TITLE
Implement Identity Server Client to authenticate using Promact OAuth Server

### ISSUE THREAD

**Issue by Krunal-Promact** [Promact/testcase-management-suite#8]
- Create Identity Server Client using OpenId
- Register Client to Identity Server
- Save Access Token in browser for further requests

**Comment by chintans** [comment]
Approved, Please provide estimated time and completion date

**Comment by Krunal-Promact** [comment]
I will complete it in 8 hours and further controller related configuration will be done in 4 hours and variable hours will be 2. so total 14 hours I will require.

**Comment by chintans** [comment]
Need a completion date too

**Comment by Krunal-Promact** [comment]
25th January will be completion date.

**Comment by Krunal-Promact** [comment]
Promact OAuth Client integrated.
